---
title: "Quiz-2 (2026.03.10) // 범위: ~01wk"
author: "최규빈"
date: "03/10/2026"
draft: false
---

## 1. 토치 텐서와 행렬 표현 매칭

다음 행렬 표현에 대응하는 올바른 torch.tensor 선언 방법을 고르시오.

`(1)` $\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$ (3×1 행렬)

① `torch.tensor([1, 2, 3])` <br>
② `torch.tensor([[1], [2], [3]])` <br>
③ `torch.tensor([[1, 2, 3]])` <br>
④ `torch.tensor([[[1]], [[2]], [[3]]])`

`(2)` $\begin{bmatrix} 1 & 2 & 3 \end{bmatrix}$ (1×3 행렬)

① `torch.tensor([1, 2, 3])`<br>
② `torch.tensor([[1], [2], [3]])` <br>
③ `torch.tensor([[1, 2, 3]])` <br>
④ `torch.tensor([[[1, 2, 3]]])`

`(3)` $\begin{bmatrix} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{bmatrix}$ (3×2 행렬)

① `torch.tensor([[1, 2], [3, 4], [5, 6]])` <br>
② `torch.tensor([[1, 3, 5], [2, 4, 6]])` <br>
③ `torch.tensor([1, 2, 3, 4, 5, 6])` <br>
④ `torch.tensor([[1, 2, 3], [4, 5, 6]])`

`(4)` $\begin{bmatrix} 5 \\ 10 \\ 15 \\ 20 \end{bmatrix}$ (4×1 행렬)

① `torch.tensor([5, 10, 15, 20])` <br>
② `torch.tensor([[5, 10, 15, 20]])` <br>
③ `torch.tensor([[5], [10], [15], [20]])` <br>
④ `torch.tensor([[[5, 10, 15, 20]]])`

`(5)` $\begin{bmatrix} 1 & 2 & 3 & 4 & 5 \end{bmatrix}$ (1×5 행렬)

① `torch.tensor([1, 2, 3, 4, 5])` <br>
② `torch.tensor([[1, 2, 3, 4, 5]])` <br>
③ `torch.tensor([[1], [2], [3], [4], [5]])` <br>
④ `torch.tensor([[[1, 2, 3, 4, 5]]])`

`(6)` $\begin{bmatrix} 2 \\ 4 \end{bmatrix}$ (2×1 행렬)

① `torch.tensor([2, 4])` <br>
② `torch.tensor([[2, 4]])` <br>
③ `torch.tensor([[2], [4]])` <br>
④ `torch.tensor([[[2]], [[4]]])`

`(7)` $\begin{bmatrix} 7 & 8 \end{bmatrix}$ (1×2 행렬)

① `torch.tensor([7, 8])` <br>
② `torch.tensor([[7, 8]])` <br>
③ `torch.tensor([[7], [8]])` <br>
④ `torch.tensor([7], [8])`

`(8)` 다음 코드로 생성된 텐서의 shape는?
```python
a = torch.tensor([[1, 2, 3]])
```

① `torch.Size([3])` <br>
② `torch.Size([1, 3])` <br>
③ `torch.Size([3, 1])` <br>
④ `torch.Size([1, 1, 3])`

`(9)` 다음 코드로 생성된 텐서의 shape는?
```python
b = torch.tensor([[1], [2], [3]])
```

① `torch.Size([3])` <br>
② `torch.Size([1, 3])` <br>
③ `torch.Size([3, 1])` <br>
④ `torch.Size([1, 1, 3])`

`(10)` 다음 코드로 생성된 텐서의 shape는?
```python
c = torch.tensor([1, 2, 3, 4])
```

① `torch.Size([4])` <br>
② `torch.Size([1, 4])` <br>
③ `torch.Size([4, 1])` <br>
④ `torch.Size([1, 1, 4])`

`(11)` 다음 코드로 생성된 텐서의 shape는?
```python
d = torch.tensor([[1, 2], [3, 4], [5, 6]])
```

① `torch.Size([3, 2])` <br>
② `torch.Size([2, 3])` <br>
③ `torch.Size([6])` <br>
④ `torch.Size([1, 3, 2])`

`(12)` 다음 코드로 생성된 텐서의 shape는?
```python
e = torch.tensor([[[1, 2, 3]]])
```
① `torch.Size([3])` <br>
② `torch.Size([1, 3])` <br>
③ `torch.Size([3, 1])` <br>
④ `torch.Size([1, 1, 3])`

## 2. 행렬 곱셉 가능 여부 판단

다음 각 경우에 대해 행렬 곱셈(`@`)이 **가능하면 "O"와 결과의 shape**를, **불가능하면 "X"**를 쓰시오.

> 답안예시:
> ```python
> torch.tensor([[1, 2]]) @ torch.tensor([[3], [4]])
> ```
> --> O, shape: 1,1

`(1)`
```python
torch.tensor([[1, 2, 3]]) @ torch.tensor([[4, 5, 6]])
```

`(2)`
```python
torch.tensor([[1, 2]]) @ torch.tensor([[3], [4]])
```

`(3)`
```python
torch.tensor([[1], [2]]) @ torch.tensor([[3, 4]])
```

`(4)`
```python
torch.tensor([[1, 2, 3, 4]]) @ torch.tensor([[5], [6], [7], [8]])
```

`(5)`
```python
torch.tensor([[1, 2], [3, 4]]) @ torch.tensor([[5, 6, 7], [8, 9, 10]])
```

`(6)`
```python
torch.tensor([[1, 2, 3]]) @ torch.tensor([[4], [5]])
```

`(7)`
```python
torch.tensor([[1], [2], [3]]) @ torch.tensor([[4, 5]])
```

`(8)`
```python
torch.tensor([[1, 2], [3, 4], [5, 6]]) @ torch.tensor([[7, 8], [9, 10]])
```

`(9)`
```python
torch.tensor([[1, 2, 3, 4, 5]]) @ torch.tensor([[6], [7], [8], [9], [10]])
```

`(10)`
```python
torch.tensor([[1], [2]]) @ torch.tensor([[3, 4], [5, 6]])
```

## 3. 역행렬 계산

**`torch`를 사용하여** 다음 행렬의 역행렬을 구하시오.

`(1)`
$$A = \begin{bmatrix} 2 & 1 & 1 \\ 1 & 2 & 1 \\ 1 & 1 & 2 \end{bmatrix}$$

`(2)`
$$B = \begin{bmatrix} 4 & 3 & 2 \\ 7 & 5 & 1 \\ 3 & 2 & 4 \end{bmatrix}$$


## 4. 행렬 슬라이싱 - 마지막 2개 열 추출

다음 5×5 행렬이 주어졌을 때:

```python
a = torch.tensor([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])
```

마지막 2개의 열(4열과 5열, 즉 인덱스 3, 4에 해당하는 열)을 추출하는 코드를 **2가지 이상의 서로 다른 방법**으로 작성하시오.
